name: Deploy Customers to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  upload-customers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install AWS CLI
      run: pip install awscli

    - name: Upload customer files to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1  # or your region
      run: |
        python <<EOF
        import json
        import subprocess
        import os

        with open("deploy-manifest.json") as f:
            manifest = json.load(f)
        
        print("Manifest loaded successfully.")

        for customer in manifest["customers"]:
            name = customer["name"]
            version = customer["version"]
            print(f"Processing customer: {name}, version: {version}")
            source_path = f"customers/{name}.json"
            s3_path = f"s3://kagr-challenge/prod/{name}/v_{version}.json"

            if os.path.isfile(source_path):
                print(f"Uploading {source_path} to {s3_path}")
                subprocess.run([
                    "aws", "s3", "cp", source_path, s3_path
                ], check=True)
            else:
                print(f"WARNING: Directory {source_path} does not exist, skipping.")
        EOF
